### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by yashksaini-coder** [AbhiDiva96/CryptoPurse#14]
Hi @AbhiDiva96 I noticed that your README contribution is severely lacking the basic guide, information & steps on what the project is and how to get started with it.

I would like to contribute to this issue and would like to work on improving the overall enhancement of the project.

Can you assign this issue to me & add labels to this issue while you are at it.

**Comment by yashksaini-coder** [comment]
@AbhiDiva96 can you assign this one too

**Comment by AbhiDiva96** [comment]
@yashksaini-coder  you can work on it

**Comment by yashksaini-coder** [comment]
Also add labels to it.
