### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [AbhiDiva96/CryptoPurse#2]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by Ishitagu** [comment]
hi ! would love to contribute to this issue please assign it to me . thank you

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of WOB24 @anusha7530 @Ishitagu @AbhiDiva96

**Comment by AbhiDiva96** [comment]
hii  @anusha7530 

I am assigning it to you to write a fresh code of conduct for the cryptoPurse.
code of conduct should be written in a clean and correct way

**Comment by KiranBaliga** [comment]
@AbhiDiva96 I guess Anusha is a part of WOB management. Can I take up this issue? 🙂

**Comment by KiranBaliga** [comment]
@AbhiDiva96 Please review the PR and share the feedback accordingly. Thank you. Please add WOB24 and Level1 label as a part of WOB campaign. Thanks again :-)

**Comment by KiranBaliga** [comment]
Please add WOB24 and Level1 label as a part of WOB campaign. Thanks again :-) 🙏
